name = "math-cilik-backend"
main = "backend/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "math-db"
database_id = "6ffb84bb-3b81-41b4-b528-772127e4f734"
